### ISSUE TITLE
Attempting to add a skript or command loot breaks that loot table in the editor

### ISSUE THREAD

**Issue by michaelabrannen** [PeriodicSeizures/LootCrates#4]
I have two loot sets that only has one item in it, which is a custom skript command. Neither of these loot sets will allow me to click into them to edit them through the editor. If I attempt to add either a "Skript" or "Command" item to any of my other existing loot sets, they also become un-editable.

my server's config: https://pastebin.com/nHC5ibap

**Comment by crazicrafter1** [comment]
Apparently I forgot to change itemStack key to item when writing both Skript loot and Command to config, which is why things were breaking, and forgot update the menu appearance. 
I just posted a release on my Discord that fixes this. Heres your working config back [https://pastebin.com/thNx39Af](url)
